### ISSUE TITLE
InflateException

### ISSUE THREAD

**Issue by krauzee** [just-ai/aimybox-android-assistant#58]
When I click on mic button my app is crashing with error:
InflateException

: Binary XML file line #2: Binary XML file line #2: You must supply a layout_width attribute.
    Caused by: java.lang.UnsupportedOperationException: Bin
ary XML file line #2: You must supply a layout_width attribute.

![image](https://user-images.githubusercontent.com/42247415/97858160-cb73a200-1d0f-11eb-9e28-4c2ea840b87c.png)

**Comment by krauzee** [comment]
android.view.InflateException: Binary XML file line #2: Binary XML file line #2: You must supply a layout_width attribute.
    Caused by: java.lang.UnsupportedOperationException: Binary XML file line #2: You must supply a layout_width attribute.
        at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:767)
        at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:7036)
        at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:7218)
        at androidx.recyclerview.widget.RecyclerView$LayoutParams.<init>(RecyclerView.java:11905)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.generateLayoutParams(RecyclerView.java:8591)
        at androidx.recyclerview.widget.RecyclerView.generateLayoutParams(RecyclerView.java:4611)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:509)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
        at com.justai.aimybox.components.extensions.ViewKt.inflate(View.kt:22)
        at com.justai.aimybox.components.extensions.ViewKt.inflate$default(View.kt:21)
        at com.justai.aimybox.components.adapter.ResponseDelegate.createViewHolder(ResponseDelegate.kt:15)
        at com.justai.aimybox.components.adapter.ResponseDelegate.createViewHolder(ResponseDelegate.kt:11)
        at com.justai.aimybox.components.base.DelegatedAdapter.onCreateViewHolder(DelegatedAdapter.kt:37)
        at com.justai.aimybox.components.base.DelegatedAdapter.onCreateViewHolder(DelegatedAdapter.kt:8)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7216)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6347)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6231)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6227)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4230)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3941)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4499)
        at android.view.View.layout(View.java:17666)
        at android.view.ViewGroup.layout(ViewGroup.java:5577)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.justai.aimybox.components.view.AimyboxButton.onLayout(AimyboxButton.kt:367)
        at android.view.View.layout(View.java:17666)
        at android.view.ViewGroup.layout(ViewGroup.java:5577)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17666)
        at android.view.ViewGroup.layout(ViewGroup.java:5577)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17666)
        at android.view.ViewGroup.layout(ViewGroup.java:5577)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17666)
        at android.view.ViewGroup.layout(ViewGroup.java:5577)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17666)
        at android.view.ViewGroup.layout(ViewGroup.java:5577)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
2020-11-02 13:30:09.558 1383-1383/ru.akbarslife.akbars E/AndroidRuntime:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
        at android.view.View.layout(View.java:17666)
        at android.view.ViewGroup.layout(ViewGroup.java:5577)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17666)
        at android.view.ViewGroup.layout(ViewGroup.java:5577)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
        at android.view.View.layout(View.java:17666)
        at android.view.ViewGroup.layout(ViewGroup.java:5577)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:730)
        at android.view.View.layout(View.java:17666)
        at android.view.ViewGroup.layout(ViewGroup.java:5577)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2390)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2112)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1298)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6437)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:876)
        at android.view.Choreographer.doCallbacks(Choreographer.java:688)
        at android.view.Choreographer.doFrame(Choreographer.java:623)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:862)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6238)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by morfeusys** [comment]
Please provide your Android version

**Comment by krauzee** [comment]
> Please provide your Android version

MIUI 11.0.2 Android 7.1.2

**Comment by Neerav006** [comment]
@krauzee just add theme in style. it should work

 <style name="Theme.VoiceSearchAmybox" parent="Theme.MaterialComponents.Light.NoActionBar">
        
        <item name="colorPrimary">@color/purple_500</item>
        <item name="colorPrimaryVariant">@color/purple_700</item>
        <item name="colorOnPrimary">@color/white</item>
        
        <item name="colorSecondary">@color/teal_200</item>
        <item name="colorSecondaryVariant">@color/teal_700</item>
        <item name="colorOnSecondary">@color/black</item>
        
        <item name="android:statusBarColor" tools:targetApi="l">?attr/colorPrimaryVariant</item>
        
        <item name="aimybox_assistantButtonTheme">@style/CustomAssistantButtonTheme</item>
        <item name="aimybox_recognitionTheme">@style/CustomRecognitionWidgetTheme</item>
        <item name="aimybox_responseTheme">@style/CustomResponseWidgetTheme</item>
        <item name="aimybox_imageReplyTheme">@style/CustomImageReplyWidgetTheme</item>
        <item name="aimybox_buttonReplyTheme">@style/CustomButtonReplyWidgetTheme</item>
    </style>

    <style name="CustomAssistantButtonTheme" parent="DefaultAssistantTheme.AssistantButton">

        

        
        
        
    </style>

    <style name="CustomRecognitionWidgetTheme" parent="DefaultAssistantTheme.Widget.Recognition">

    </style>

    <style name="CustomResponseWidgetTheme" parent="DefaultAssistantTheme.Widget.Response">

    </style>

    <style name="CustomButtonReplyWidgetTheme" parent="DefaultAssistantTheme.Widget.ButtonReply">

    </style>

    <style name="CustomImageReplyWidgetTheme" parent="DefaultAssistantTheme.Widget.ImageReply">

    </style>

**Comment by Neerav006** [comment]
Just put these styles in theme.xml file it should work

 <style name="Theme.VoiceSearchAmybox" parent="Theme.MaterialComponents.Light.NoActionBar">
        
        <item name="colorPrimary">@color/purple_500</item>
        <item name="colorPrimaryVariant">@color/purple_700</item>
        <item name="colorOnPrimary">@color/white</item>
        
        <item name="colorSecondary">@color/teal_200</item>
        <item name="colorSecondaryVariant">@color/teal_700</item>
        <item name="colorOnSecondary">@color/black</item>
        
        <item name="android:statusBarColor" tools:targetApi="l">?attr/colorPrimaryVariant</item>
        
        <item name="aimybox_assistantButtonTheme">@style/CustomAssistantButtonTheme</item>
        <item name="aimybox_recognitionTheme">@style/CustomRecognitionWidgetTheme</item>
        <item name="aimybox_responseTheme">@style/CustomResponseWidgetTheme</item>
        <item name="aimybox_imageReplyTheme">@style/CustomImageReplyWidgetTheme</item>
        <item name="aimybox_buttonReplyTheme">@style/CustomButtonReplyWidgetTheme</item>
    </style>

    <style name="CustomAssistantButtonTheme" parent="DefaultAssistantTheme.AssistantButton">

        

        
        
        
    </style>

    <style name="CustomRecognitionWidgetTheme" parent="DefaultAssistantTheme.Widget.Recognition">

    </style>

    <style name="CustomResponseWidgetTheme" parent="DefaultAssistantTheme.Widget.Response">

    </style>

    <style name="CustomButtonReplyWidgetTheme" parent="DefaultAssistantTheme.Widget.ButtonReply">

    </style>

    <style name="CustomImageReplyWidgetTheme" parent="DefaultAssistantTheme.Widget.ImageReply">

    </style>

**Comment by krauzee** [comment]
I added this to my styles.xml
![image](https://user-images.githubusercontent.com/42247415/99688964-7073d600-2a97-11eb-9709-3385c310e597.png)

but I still get the error. What am I doing wrong?
![image](https://user-images.githubusercontent.com/42247415/99689071-913c2b80-2a97-11eb-8c3b-2a05e66a107f.png)

**Comment by Billthebest1** [comment]
youre in better shape than me im compleatly new to this have android studio and dont have a clue on how to get a assisstant app to work lol ive tryied them all  this one seems the closest to the one i had but google got rid of  it even works with dialogue flo  but i cant get it to work im missing something in the instructions on how to do it and every time i try i end up downloading more and more software it went from android studio to github desktop to some thing that starts with z i cant think of the name atm  i just want a assisstant app like the one i paid for the one by speaktoit that one was perfect it was eficiant ran everything so useful af plus customizable and funny and its like im going to have to take 8 years of college in order to get it back

**Comment by morfeusys** [comment]
@krauzee are you sure you've applied this style in your AndroidManifest?

**Comment by krauzee** [comment]
I solved this problem, thanks

**Comment by morfeusys** [comment]
@krauzee did my suggest help you or you've found another solution?

**Comment by krauzee** [comment]
> @krauzee did my suggest help you or you've found another solution?

your suggestion helped me, thanks!
